#!/bin/bash
# curl -fsSL https://raw.githubusercontent.com/jeffvsutherland/agent-security-framework/main/asf-cio-security-report.sh | bash

OUTPUT_FILE="ASF-CIO-SECURITY-REPORT.md"
DATE=$(date '+%Y-%m-%d %H:%M:%S')

echo "🛡️ Generating CIO Security Report..."

# Clean old scan results
rm -f asf-openclaw-scan-report.json ~/asf-openclaw-scan-report.json

# Download scanner if not present
if [ ! -f "asf-openclaw-scanner.py" ]; then
    echo "Downloading security scanner..."
    curl -sSL "https://raw.githubusercontent.com/jeffvsutherland/agent-security-framework/main/asf-openclaw-scanner.py" -o asf-openclaw-scanner.py
    chmod +x asf-openclaw-scanner.py
fi

# Run scanner - let it auto-detect skills path
echo "Running security scan..."
python3 asf-openclaw-scanner.py 2>&1 || true

# Find JSON
JSON_FILE=""
for f in asf-openclaw-scan-report.json /workspace/asf-openclaw-scan-report.json ~/asf-openclaw-scan-report.json; do
  [ -f "$f" ] && JSON_FILE="$f" && break
done

# Default
SCORE=100; WARNINGS=0; DANGERS=0; UNFIXED_LIST=""

if [ -n "$JSON_FILE" ] && [ -r "$JSON_FILE" ]; then
    SCORE=$(python3 -c "import json; print(json.load(open('$JSON_FILE')).get('summary',{}).get('security_score',100))" 2>/dev/null || echo "100")
    WARNINGS=$(python3 -c "import json; print(json.load(open('$JSON_FILE')).get('summary',{}).get('warning_skills',0))" 2>/dev/null || echo "0")
    DANGERS=$(python3 -c "import json; print(json.load(open('$JSON_FILE')).get('summary',{}).get('danger_skills',0))" 2>/dev/null || echo "0")
    
    # Get unfixed skills
    UNFIXED_LIST=$(python3 -c "
import json
try:
    data = json.load(open('$JSON_FILE'))
    fixes = data.get('fixes_status', {})
    unfixed = [f'{k}: {v}' for k, v in fixes.items() if 'NOT' in v]
    print('; '.join(unfixed) if unfixed else 'All skills secured')
except: print('Unknown')
" 2>/dev/null || echo "Unknown")
fi

# Status
if [ "$SCORE" -eq 100 ]; then STATUS="✅ PERFECT"; elif [ "$SCORE" -ge 90 ]; then STATUS="✅ EXCELLENT"; elif [ "$SCORE" -ge 70 ]; then STATUS="⚠️ ACCEPTABLE"; else STATUS="❌ CRITICAL"; fi
[ "$DANGERS" -eq 0 ] && CRIT="✅ None" || CRIT="❌ ACTION REQUIRED"
[ "$WARNINGS" -gt 0 ] && WARN_STATUS="⚠️ $WARNINGS to review" || WARN_STATUS="✅ None"
[ "$SCORE" -eq 100 ] && MEANING="fully secured - 100/100!" || [ "$SCORE" -ge 90 ] && MEANING="well-protected" || [ "$SCORE" -ge 70 ] && MEANING="adequately protected" || MEANING="requiring attention"
SAFE=$((52 - WARNINGS - DANGERS)); [ $SAFE -lt 0 ] && SAFE=0

# Generate report
cat > "$OUTPUT_FILE" << EOF
# ASF Security Report - Executive Summary

**Generated:** $DATE  
**System:** OpenClaw Agent Platform  
**Security Score:** $SCORE/100 $STATUS

---

## Overall Status

| Metric | Value | Status |
|--------|-------|--------|
| Security Score | $SCORE/100 | $STATUS |
| Safe Skills | $SAFE | ✅ Pass |
| Warning Skills | $WARNINGS | $WARN_STATUS |
| Critical Issues | $DANGERS | $CRIT |

---

## Score Details

**Unfixed Skills:** $UNFIXED_LIST

---

## What This Score Means

Your security score of **$SCORE/100** indicates the system is **$MEANING**.

---

## Components Passing ✅

- ASF-42 Syscall Monitor ✅
- ASF-41 Guardrail ✅
- ASF-38 Trust Score ✅
- ASF-37 Spam Filter ✅
- ASF-5 YARA Scanner ✅
- ASF-18 Code Review ✅

---

## Issues

### Critical Issues

$([ "$DANGERS" -eq 0 ] && echo "✅ **None** - No critical issues found" || echo "🚨 **$DANGERS** critical issue(s) found")

---

## Next Steps

1. System is $MEANING
2. Run scanner in OpenClaw for details

---
*Generated by ASF Security Framework*
EOF

echo "✅ CIO Report: $OUTPUT_FILE"
cat "$OUTPUT_FILE"
