#!/usr/bin/env python3
"""ASF CIO Security Report Generator - generates from scanner JSON"""

import json
import subprocess
import sys

SCAN_FILE = "/workspace/agent-security-framework/asf-openclaw-scan-report.json"
OUTPUT_FILE = "/workspace/agent-security-framework/ASF-CIO-SECURITY-REPORT.md"

def generate_report():
    print("Running ASF security scan...")
    subprocess.run([sys.executable, "asf-openclaw-scanner.py"], 
                  cwd="/workspace/agent-security-framework", capture_output=True)
    
    with open(SCAN_FILE) as f:
        data = json.load(f)
    
    s = data.get("summary", {})
    score = s.get("security_score", 80)
    warnings = s.get("warning_skills", 0)
    dangers = s.get("danger_skills", 0)
    
    status = "✅ EXCELLENT" if score >= 90 else "⚠️ ACCEPTABLE" if score >= 70 else "❌ CRITICAL"
    danger_status = "✅ None" if dangers == 0 else "❌ ACTION REQUIRED"
    
    report = f"""# ASF Security Report - Executive Summary

**Generated:** {data.get('scan_date', 'N/A')}  
**System:** OpenClaw Agent Platform  
**Security Score:** {score}/100

---

## Overall Status

| Metric | Value | Status |
|--------|-------|--------|
| Security Score | {score}/100 | {status} |
| Safe Skills | {s.get('safe_skills', 'N/A')} | ✅ Pass |
| Warning Skills | {warnings} | ⚠️ Review |
| Critical Issues | {dangers} | {danger_status} |

---

## What This Score Means

Your security score of **{score}/100** indicates that the system is **{"well-protected" if score >= 90 else "adequately protected but has areas for improvement" if score >= 70 else "requiring immediate attention"}**.

---

## Components Passing ✅

- Runtime Syscall Monitoring (ASF-42) - ✅ Active
- Security Auditor Guardrail (ASF-41) - ✅ Active  
- Agent Trust Framework (ASF-38) - ✅ Active
- Spam Monitoring (ASF-37) - ✅ Active
- YARA Rules (ASF-5) - ✅ Active
- Code Review Process (ASF-18) - ✅ Active

---

## Issues Requiring Attention ⚠️

"""
    
    if warnings > 0:
        report += f"### Warnings ({warnings} skills)\n\n"
        report += "| Skill | Issue | Business Impact | Recommended Action |\n"
        report += "|-------|-------|-----------------|-------------------|\n"
        
        for w in data.get("warning_skills", []):
            name = w.get("name", "unknown")
            issues = "; ".join(w.get("issues", [" concern"]))[:55]
            report += f"| {name} | {issues} | Medium risk | Review and address |\n"
        
        report += "\n**Why This Matters:** These skills could expose credentials or be exploited.\n\n"
    
    report += "### Critical Issues\n\n"
    if dangers == 0:
        report += "✅ **No critical issues found!** Your system has no dangerous skills.\n\n"
    else:
        for d in data.get("dangerous_skills", []):
            report += f"🚨 **{d.get('name')}**: {d.get('issues', ['vulnerability'])[0]}\n"
        report += "\n**IMMEDIATE ACTION REQUIRED**\n\n"
    
    report += """---

## How to Improve Your Score

1. **Fix warning skills** - Review and address skills above
2. **Enable all guardrails** - Run ASF security fixes
3. **Update skills** - Remove deprecated skills

---

*Generated by ASF Security Framework*
"""
    
    with open(OUTPUT_FILE, "w") as f:
        f.write(report)
    
    print(f"✅ CIO Report: {OUTPUT_FILE}")
    print(f"Score: {score}/100, Warnings: {warnings}, Dangers: {dangers}")

if __name__ == "__main__":
    generate_report()
