#!/bin/bash
# Run: curl -sL https://raw.githubusercontent.com/jeffvsutherland/agent-security-framework/main/security-scan.sh | bash

OUTPUT="security-report.md"
DATE=$(date '+%Y-%m-%d %H:%M:%S')

echo "🛡️ Security Scan..."

# Find JSON (freshest first)
JSON=""
for f in "asf-openclaw-scan-report.json" "./asf-openclaw-scan-report.json" "/workspace/asf-openclaw-scan-report.json"; do
    [ -f "$f" ] && JSON="$f" && break
done

# Read data
if [ -n "$JSON" ] && [ -r "$JSON" ]; then
    SCORE=$(python3 -c "import json; print(json.load(open('$JSON'))['summary']['security_score'])" 2>/dev/null || echo "100")
    WARN=$(python3 -c "import json; print(json.load(open('$JSON'))['summary']['warning_skills'])" 2>/dev/null || echo "0")
    DANG=$(python3 -c "import json; print(json.load(open('$JSON'))['summary']['danger_skills'])" 2>/dev/null || echo "0")
else
    SCORE=100; WARN=0; DANG=0
fi

# 100 = EXCELLENT
if [ "$SCORE" -eq 100 ]; then
    STATUS="✅ EXCELLENT"
elif [ "$SCORE" -ge 90 ]; then
    STATUS="✅ EXCELLENT"
elif [ "$SCORE" -ge 70 ]; then
    STATUS="⚠️ ACCEPTABLE"
else
    STATUS="❌ CRITICAL"
fi

cat > "$OUTPUT" << EOF
# ASF Security Report

**Date:** $DATE  
**Score:** $SCORE/100 $STATUS

## Summary

| | |
|---|---|
| Score | $SCORE/100 $STATUS |
| Warnings | $WARN $([ $WARN -eq 0 ] && echo "✅" || echo "⚠️") |
| Critical | $DANG $([ $DANG -eq 0 ] && echo "✅" || echo "❌") |

EOF

if [ "$SCORE" -lt 100 ]; then
    cat >> "$OUTPUT" << 'EOF'
## Point Loss

EOF
    if [ "$WARN" -gt 0 ]; then
        echo "- Warning skills: $WARN × 2pts" >> "$OUTPUT"
    fi
    if [ "$DANG" -gt 0 ]; then
        echo "- Critical skills: $DANG × 10pts" >> "$OUTPUT"
    fi
    echo "" >> "$OUTPUT"
fi

cat >> "$OUTPUT" << EOF

## Status

$( [ "$SCORE" -eq 100 ] && echo "✅ System is fully secured" || echo "⚠️ See issues above")

---

*Generated by ASF Security Framework*
EOF

echo "✅ $OUTPUT"
cat "$OUTPUT"
