#!/bin/bash
# Run fresh: curl -sL https://raw.githubusercontent.com/jeffvsutherland/agent-security-framework/main/security-scan.sh | bash

OUTPUT="security-report.md"
DATE=$(date '+%Y-%m-%d %H:%M:%S')

echo "🛡️ Security Scan..."

# Find JSON (freshest first - current dir)
JSON=""
for f in "asf-openclaw-scan-report.json" "./asf-openclaw-scan-report.json" "/workspace/asf-openclaw-scan-report.json"; do
    [ -f "$f" ] && JSON="$f" && break
done

# Read data
if [ -n "$JSON" ] && [ -r "$JSON" ]; then
    SCORE=$(python3 -c "import json; print(json.load(open('$JSON'))['summary']['security_score'])" 2>/dev/null || echo "100")
    WARN=$(python3 -c "import json; print(json.load(open('$JSON'))['summary']['warning_skills'])" 2>/dev/null || echo "0")
    DANG=$(python3 -c "import json; print(json.load(open('$JSON'))['summary']['danger_skills'])" 2>/dev/null || echo "0")
else
    SCORE=100; WARN=0; DANG=0
fi

# FIX: 100 should be EXCELLENT, not ACCEPTABLE
if [ "$SCORE" -eq 100 ]; then
    STATUS="✅ EXCELLENT"
elif [ "$SCORE" -ge 90 ]; then
    STATUS="✅ EXCELLENT"
elif [ "$SCORE" -ge 70 ]; then
    STATUS="⚠️ ACCEPTABLE"
else
    STATUS="❌ CRITICAL"
fi

cat > "$OUTPUT" << EOF
# ASF Security Report

**Date:** $DATE  
**Score:** $SCORE/100 $STATUS

## Summary

| | |
|---|---|
| Score | $SCORE/100 $STATUS |
| Warnings | $WARN $([ $WARN -eq 0 ] && echo "✅ None" || echo "⚠️ Review") |
| Critical | $DANG $([ $DANG -eq 0 ] && echo "✅ None" || echo "❌ ACTION") |

EOF

if [ "$SCORE" -lt 100 ]; then
    UNFIXED=$(python3 -c "
import json
for skill, status in json.load(open('$JSON')).get('fixes_status', {}).items():
    if status == 'NOT_FIXED':
        print(f'  - {skill}: NOT_FIXED (-2 pts)')
" 2>/dev/null)
    [ -z "$UNFIXED" ] && UNFIXED="  (none)"
    
    cat >> "$OUTPUT" << EOF

## Point Loss Details

$UNFIXED

EOF
fi

cat >> "$OUTPUT" << EOF

## Components ✅

- ASF-42 Syscall Monitor ✅
- ASF-41 Guardrail ✅
- ASF-38 Trust Score ✅
- ASF-37 Spam Filter ✅
- ASF-5 YARA Scanner ✅

---

*Generated by ASF Security Framework*
EOF

echo "✅ $OUTPUT"
cat "$OUTPUT"
