#!/bin/bash
# ASF Daily Security Report Generator
# Run daily via cron: 0 6 * * * /path/to/asf-daily-report.sh

REPORT_DIR="/var/log/asf/reports"
DATE=$(date +%Y%m%d)
REPORT_FILE="$REPORT_DIR/asf-daily-report-$DATE.md"

mkdir -p "$REPORT_DIR"

echo "# ASF Daily Security Report - $DATE" > "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "Generated: $(date)" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# Run YARA scan
echo "## YARA Scan Results" >> "$REPORT_FILE"
if command -v yara &> /dev/null; then
    yara -r /path/to/asf-5-yara-rules/*.yar /path/to/.openclaw/ 2>/dev/null >> "$REPORT_FILE" || echo "No threats detected" >> "$REPORT_FILE"
else
    echo "YARA not installed" >> "$REPORT_FILE"
fi
echo "" >> "$REPORT_FILE"

# Run trust check
echo "## Trust Score (ASF-38)" >> "$REPORT_FILE"
if [ -f "../docs/asf-38-agent-trust-framework/asf-trust-check.py" ]; then
    python3 ../docs/asf-38-agent-trust-framework/asf-trust-check.py /path/to/.openclaw >> "$REPORT_FILE" 2>&1 || echo "Trust check failed" >> "$REPORT_FILE"
fi
echo "" >> "$REPORT_FILE"

# Spam monitoring
echo "## Spam Monitoring (ASF-37)" >> "$REPORT_FILE"
if [ -f "$HOME/.asf/logs/spam-monitor.log" ]; then
    tail -20 "$HOME/.asf/logs/spam-monitor.log" >> "$REPORT_FILE"
else
    echo "No spam alerts" >> "$REPORT_FILE"
fi
echo "" >> "$REPORT_FILE"

# Container status
echo "## Container Status" >> "$REPORT_FILE"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" >> "$REPORT_FILE" 2>/dev/null || echo "Docker not available" >> "$REPORT_FILE"

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Report generated by ASF Daily Security Report Generator*" >> "$REPORT_FILE"

echo "✅ Daily report generated: $REPORT_FILE"

# Also output to stdout
cat "$REPORT_FILE"
