#!/usr/bin/env python3
"""
ASF Fix Prompt Generator
Reads CIO security report and generates actionable fix prompts for agents.
"""

import sys
import re

def parse_cio_report(filename):
    """Parse CIO report and extract failing components"""
    with open(filename, 'r') as f:
        content = f.read()
    
    fixes = []
    
    # Extract failing components
    sections = content.split('### ')
    for section in sections:
        if '❌' in section or 'FAIL' in section or 'Issues' in section:
            lines = section.split('\n')
            component = ""
            for line in lines:
                if '**' in line:
                    component = line.replace('**', '').strip()
                if 'Recommendation' in line or 'recommendation' in line:
                    fixes.append(component)
    
    return fixes

def generate_fix_prompts(fixes):
    """Generate markdown with fix prompts"""
    output = "# ASF Security Fix Prompts\n\n"
    output += "Generated from CIO Security Report\n\n"
    output += "---\n\n"
    
    for fix in fixes:
        output += f"## Fix: {fix}\n\n"
        output += "### Problem\n"
        output += f"{fix} is not functioning properly.\n\n"
        output += "### Fix Command\n"
        output += "```bash\n"
        output += f"# Run {fix} setup\n"
        output += "cd ~/agent-security-framework\n"
        output += "./docs/asf-*-*/setup.sh\n"
        output += "```\n\n"
        output += "### Verification\n"
        output += "```bash\n"
        output += "# Verify it's working\n"
        output += "python3 generate-cio-security-report.py\n"
        output += "```\n\n"
    
    output += "---\n*Generated by ASF Fix Prompt Generator*\n"
    return output

def main():
    input_file = sys.argv[1] if len(sys.argv) > 1 else "ASF-CIO-SECURITY-REPORT.md"
    output_file = sys.argv[2] if len(sys.argv) > 2 else "FIX-PROMPTS.md"
    
    print(f"Reading: {input_file}")
    fixes = parse_cio_report(input_file)
    print(f"Found {len(fixes)} issues to fix")
    
    output = generate_fix_prompts(fixes)
    
    with open(output_file, 'w') as f:
        f.write(output)
    
    print(f"Written to: {output_file}")
    print("\nFix prompts generated!")

if __name__ == "__main__":
    main()
